name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Install dependencies
        run: 
          sudo apt install ssh curl php php-curl mysql-server composer npm
      - name: Clone repo
        run: 
          git clone https://github.com/Emil766321/Vision
      - name: Build App
        run:
          cd Vision
          &&
          composer update
          && 
          composer install --no-dev --optimize-autoloader
          &&
          npm install
          &&
          cp .env.example .env
          &&
          sed 's/APP_ENV.*/APP_ENV=production/g' .env
          &&
          sed 's/APP_DEBUG.*/APP_DEBUG=false/g' .env
          &&
          sed 's/DB_HOST.*/DB_HOST=127.0.0.1/g' .env
          &&
          sed 's/DB_PORT.*/DB_PORT=3306/g' .env
          &&
          sed 's/DB_DATABASE.*/DB_DATABASE=${{ secrets.DB_NAME }}/g' .env
          &&
          sed 's/DB_USERNAME.*/DB_USERNAME=${{ secrets.DB_USERNAME_TEST }}/g' .env
          &&
          sed 's/DB_PASSWORD.*/DB_PASSWORD=/g' .env
          &&
          cat .env
