name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Install dependencies
        run: 
          sudo apt install ssh curl php php-curl mysql-server composer npm
      - name: Clone repo
        run: 
          git clone https://github.com/Emil766321/Vision
      - name: Build App
        run:
          cd Vision
          &&
          composer update
          && 
          composer install --no-dev --optimize-autoloader
          &&
          npm install
          &&
          cp .env.example .env
          &&
          sed -i "/^APP_ENV=/s/.*/APP_ENV=production/" .env
          &&
          sed -i "/^DB_DATABASE=/s/.*/DB_DATABASE=${{ secrets.DB_NAME }}/" .env
          &&
          cat .env
