name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Install dependencies
        run: 
          sudo apt install ssh curl php php-curl mysql-server composer npm
      - name: Clone repo
        run: 
          git clone https://github.com/Emil766321/Vision
      - name: Open repository
        run:
          cd Vision
          && 
          composer install
      - name: Build app
        run:
          ls
          
